version: '3.4'

services:
  api:
    build: 
      context: ./api/KnowledgeGraph/KnowledgeGraph
    ports:
      - "80:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Local 

  database:
    image: neo4j:3.5
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./.neo4j/conf:/conf
      - ./.neo4j/data:/data
      - ./.neo4j/logs:/logs

  aws-local:
    image: localstack/localstack
    ports:
      - "4572:4572"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=s3

  frontend:
    build: 
      context: ./frontend
      target: develop
    image: frontend:latest
    volumes:
      - ./frontend:/usr/frontend/app 
    ports:
      - "3000:3000"
  
