// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace KnowledgeGraphSdk
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// Extension methods for KnowledgeGraphSdkClient.
    /// </summary>
    public static partial class KnowledgeGraphSdkClientExtensions
    {
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='searchTerm'>
            /// </param>
            public static object ListClinicalTrials(this IKnowledgeGraphSdkClient operations, string searchTerm)
            {
                return Task.Factory.StartNew(s => ((IKnowledgeGraphSdkClient)s).ListClinicalTrialsAsync(searchTerm), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='searchTerm'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> ListClinicalTrialsAsync(this IKnowledgeGraphSdkClient operations, string searchTerm, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ListClinicalTrialsWithHttpMessagesAsync(searchTerm, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
