// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace KnowledgeGraphSdk.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// the data from a clinical trial
    /// </summary>
    public partial class ClinicalTrial
    {
        /// <summary>
        /// Initializes a new instance of the ClinicalTrial class.
        /// </summary>
        public ClinicalTrial() { }

        /// <summary>
        /// Initializes a new instance of the ClinicalTrial class.
        /// </summary>
        public ClinicalTrial(string briefSummary = default(string), string briefTitle = default(string), double? latitude = default(double?), double? longitude = default(double?), string nctId = default(string), string officialTitle = default(string), string orgStudyId = default(string), string url = default(string))
        {
            BriefSummary = briefSummary;
            BriefTitle = briefTitle;
            Latitude = latitude;
            Longitude = longitude;
            NctId = nctId;
            OfficialTitle = officialTitle;
            OrgStudyId = orgStudyId;
            Url = url;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "brief_summary")]
        public string BriefSummary { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "brief_title")]
        public string BriefTitle { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "latitude")]
        public double? Latitude { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "longitude")]
        public double? Longitude { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "nct_id")]
        public string NctId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "official_title")]
        public string OfficialTitle { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "org_study_id")]
        public string OrgStudyId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "url")]
        public string Url { get; set; }

    }
}
