// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace KnowledgeGraphSdk.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// the detail location info of a clinical trial
    /// </summary>
    public partial class DetailLocation
    {
        /// <summary>
        /// Initializes a new instance of the DetailLocation class.
        /// </summary>
        public DetailLocation() { }

        /// <summary>
        /// Initializes a new instance of the DetailLocation class.
        /// </summary>
        public DetailLocation(string city = default(string), string country = default(string), string lat = default(string), string lng = default(string), string name = default(string), string newId = default(string), string state = default(string), string zip = default(string))
        {
            City = city;
            Country = country;
            Lat = lat;
            Lng = lng;
            Name = name;
            NewId = newId;
            State = state;
            Zip = zip;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "city")]
        public string City { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "country")]
        public string Country { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lat")]
        public string Lat { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lng")]
        public string Lng { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "new_id")]
        public string NewId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "state")]
        public string State { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "zip")]
        public string Zip { get; set; }

    }
}
