// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace KnowledgeGraphSdk.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// the detailed data from a clinical trial
    /// </summary>
    public partial class DetailResponse
    {
        /// <summary>
        /// Initializes a new instance of the DetailResponse class.
        /// </summary>
        public DetailResponse() { }

        /// <summary>
        /// Initializes a new instance of the DetailResponse class.
        /// </summary>
        public DetailResponse(IList<DetailAgeRange> ageRanges = default(IList<DetailAgeRange>), string briefSummary = default(string), string briefTitle = default(string), IList<DetailCondition> conditions = default(IList<DetailCondition>), IList<DetailContact> contacts = default(IList<DetailContact>), string criteriaText = default(string), IList<DetailSex> genders = default(IList<DetailSex>), IList<DetailHealthyVolunteers> healthyVolunteers = default(IList<DetailHealthyVolunteers>), IList<DetailIntervention> interventions = default(IList<DetailIntervention>), IList<DetailLocation> locations = default(IList<DetailLocation>), string maximumAge = default(string), IList<DetailMeshTerm> meshTerms = default(IList<DetailMeshTerm>), string minimumAge = default(string), string nctId = default(string), string newId = default(string), string officialTitle = default(string), string orgStudyId = default(string), string overallStatus = default(string), string phase = default(string), IList<DetailAgency> sponsors = default(IList<DetailAgency>), string startDate = default(string), string startYear = default(string), string studyType = default(string), string url = default(string))
        {
            AgeRanges = ageRanges;
            BriefSummary = briefSummary;
            BriefTitle = briefTitle;
            Conditions = conditions;
            Contacts = contacts;
            CriteriaText = criteriaText;
            Genders = genders;
            HealthyVolunteers = healthyVolunteers;
            Interventions = interventions;
            Locations = locations;
            MaximumAge = maximumAge;
            MeshTerms = meshTerms;
            MinimumAge = minimumAge;
            NctId = nctId;
            NewId = newId;
            OfficialTitle = officialTitle;
            OrgStudyId = orgStudyId;
            OverallStatus = overallStatus;
            Phase = phase;
            Sponsors = sponsors;
            StartDate = startDate;
            StartYear = startYear;
            StudyType = studyType;
            Url = url;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "age_ranges")]
        public IList<DetailAgeRange> AgeRanges { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "brief_summary")]
        public string BriefSummary { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "brief_title")]
        public string BriefTitle { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "conditions")]
        public IList<DetailCondition> Conditions { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "contacts")]
        public IList<DetailContact> Contacts { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "criteria_text")]
        public string CriteriaText { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "genders")]
        public IList<DetailSex> Genders { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "healthy_volunteers")]
        public IList<DetailHealthyVolunteers> HealthyVolunteers { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "interventions")]
        public IList<DetailIntervention> Interventions { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "locations")]
        public IList<DetailLocation> Locations { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "maximum_age")]
        public string MaximumAge { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "mesh_terms")]
        public IList<DetailMeshTerm> MeshTerms { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "minimum_age")]
        public string MinimumAge { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "nct_id")]
        public string NctId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "new_id")]
        public string NewId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "official_title")]
        public string OfficialTitle { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "org_study_id")]
        public string OrgStudyId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "overall_status")]
        public string OverallStatus { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "phase")]
        public string Phase { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "sponsors")]
        public IList<DetailAgency> Sponsors { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "start_date")]
        public string StartDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "start_year")]
        public string StartYear { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "study_type")]
        public string StudyType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "url")]
        public string Url { get; set; }

    }
}
