// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace KnowledgeGraphSdk.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// the detail agency of a clinical trial
    /// </summary>
    public partial class DetailAgency
    {
        /// <summary>
        /// Initializes a new instance of the DetailAgency class.
        /// </summary>
        public DetailAgency() { }

        /// <summary>
        /// Initializes a new instance of the DetailAgency class.
        /// </summary>
        public DetailAgency(string agency = default(string), string newId = default(string))
        {
            Agency = agency;
            NewId = newId;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "agency")]
        public string Agency { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "new_id")]
        public string NewId { get; set; }

    }
}
