// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace KnowledgeGraphSdk.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// the detail intervention of a clinical trial
    /// </summary>
    public partial class DetailIntervention
    {
        /// <summary>
        /// Initializes a new instance of the DetailIntervention class.
        /// </summary>
        public DetailIntervention() { }

        /// <summary>
        /// Initializes a new instance of the DetailIntervention class.
        /// </summary>
        public DetailIntervention(string interventionName = default(string), string newId = default(string))
        {
            InterventionName = interventionName;
            NewId = newId;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "intervention_name")]
        public string InterventionName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "new_id")]
        public string NewId { get; set; }

    }
}
