// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace KnowledgeGraphSdk.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// the detail healthy volunteers of a clinical trial
    /// </summary>
    public partial class DetailHealthyVolunteers
    {
        /// <summary>
        /// Initializes a new instance of the DetailHealthyVolunteers class.
        /// </summary>
        public DetailHealthyVolunteers() { }

        /// <summary>
        /// Initializes a new instance of the DetailHealthyVolunteers class.
        /// </summary>
        public DetailHealthyVolunteers(string healthyVolunteers = default(string), string newId = default(string))
        {
            HealthyVolunteers = healthyVolunteers;
            NewId = newId;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "healthy_volunteers")]
        public string HealthyVolunteers { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "new_id")]
        public string NewId { get; set; }

    }
}
