// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace KnowledgeGraphSdk.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// the detail mesh term of a clinical trial
    /// </summary>
    public partial class DetailMeshTerm
    {
        /// <summary>
        /// Initializes a new instance of the DetailMeshTerm class.
        /// </summary>
        public DetailMeshTerm() { }

        /// <summary>
        /// Initializes a new instance of the DetailMeshTerm class.
        /// </summary>
        public DetailMeshTerm(string meshTerm = default(string), string newId = default(string))
        {
            MeshTerm = meshTerm;
            NewId = newId;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "mesh_term")]
        public string MeshTerm { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "new_id")]
        public string NewId { get; set; }

    }
}
