// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace KnowledgeGraphSdk.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// the detail contact of a clinical trial
    /// </summary>
    public partial class DetailContact
    {
        /// <summary>
        /// Initializes a new instance of the DetailContact class.
        /// </summary>
        public DetailContact() { }

        /// <summary>
        /// Initializes a new instance of the DetailContact class.
        /// </summary>
        public DetailContact(string degrees = default(string), string email = default(string), string firstName = default(string), string investigatorFullName = default(string), string investigatorTitle = default(string), string lastName = default(string), string middleName = default(string), string nameTitle = default(string), string newId = default(string), string phone = default(string), string phoneExt = default(string))
        {
            Degrees = degrees;
            Email = email;
            FirstName = firstName;
            InvestigatorFullName = investigatorFullName;
            InvestigatorTitle = investigatorTitle;
            LastName = lastName;
            MiddleName = middleName;
            NameTitle = nameTitle;
            NewId = newId;
            Phone = phone;
            PhoneExt = phoneExt;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "degrees")]
        public string Degrees { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "email")]
        public string Email { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "first_name")]
        public string FirstName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "investigator_full_name")]
        public string InvestigatorFullName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "investigator_title")]
        public string InvestigatorTitle { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "last_name")]
        public string LastName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "middle_name")]
        public string MiddleName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name_title")]
        public string NameTitle { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "new_id")]
        public string NewId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "phone")]
        public string Phone { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "phone_ext")]
        public string PhoneExt { get; set; }

    }
}
