// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace KnowledgeGraphSdk.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// data indicating error conditions
    /// </summary>
    public partial class ErrorResponse
    {
        /// <summary>
        /// Initializes a new instance of the ErrorResponse class.
        /// </summary>
        public ErrorResponse() { }

        /// <summary>
        /// Initializes a new instance of the ErrorResponse class.
        /// </summary>
        public ErrorResponse(string errorDescription = default(string), long? errorNumber = default(long?), string parameterName = default(string), string parameterValue = default(string))
        {
            ErrorDescription = errorDescription;
            ErrorNumber = errorNumber;
            ParameterName = parameterName;
            ParameterValue = parameterValue;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "error_description")]
        public string ErrorDescription { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "error_number")]
        public long? ErrorNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "parameter_name")]
        public string ParameterName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "parameter_value")]
        public string ParameterValue { get; set; }

    }
}
