// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace KnowledgeGraphSdk.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// the list data from a clinical trial
    /// </summary>
    public partial class ListClinicalTrial
    {
        /// <summary>
        /// Initializes a new instance of the ListClinicalTrial class.
        /// </summary>
        public ListClinicalTrial() { }

        /// <summary>
        /// Initializes a new instance of the ListClinicalTrial class.
        /// </summary>
        public ListClinicalTrial(string briefSummary = default(string), string briefTitle = default(string), string criteriaText = default(string), IList<ListLocation> locations = default(IList<ListLocation>), string maximumAge = default(string), string minimumAge = default(string), string nctId = default(string), string newId = default(string), string officialTitle = default(string), string orgStudyId = default(string), string overallStatus = default(string), string phase = default(string), string startDate = default(string), string startYear = default(string), string studyType = default(string), string url = default(string))
        {
            BriefSummary = briefSummary;
            BriefTitle = briefTitle;
            CriteriaText = criteriaText;
            Locations = locations;
            MaximumAge = maximumAge;
            MinimumAge = minimumAge;
            NctId = nctId;
            NewId = newId;
            OfficialTitle = officialTitle;
            OrgStudyId = orgStudyId;
            OverallStatus = overallStatus;
            Phase = phase;
            StartDate = startDate;
            StartYear = startYear;
            StudyType = studyType;
            Url = url;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "brief_summary")]
        public string BriefSummary { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "brief_title")]
        public string BriefTitle { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "criteria_text")]
        public string CriteriaText { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "locations")]
        public IList<ListLocation> Locations { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "maximum_age")]
        public string MaximumAge { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "minimum_age")]
        public string MinimumAge { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "nct_id")]
        public string NctId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "new_id")]
        public string NewId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "official_title")]
        public string OfficialTitle { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "org_study_id")]
        public string OrgStudyId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "overall_status")]
        public string OverallStatus { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "phase")]
        public string Phase { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "start_date")]
        public string StartDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "start_year")]
        public string StartYear { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "study_type")]
        public string StudyType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "url")]
        public string Url { get; set; }

    }
}
