// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace KnowledgeGraphSdk.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// data included from the search response
    /// </summary>
    public partial class SearchResponse
    {
        /// <summary>
        /// Initializes a new instance of the SearchResponse class.
        /// </summary>
        public SearchResponse() { }

        /// <summary>
        /// Initializes a new instance of the SearchResponse class.
        /// </summary>
        public SearchResponse(bool? lastPage = default(bool?), long? numResults = default(long?), long? page = default(long?), IList<ListClinicalTrial> results = default(IList<ListClinicalTrial>))
        {
            LastPage = lastPage;
            NumResults = numResults;
            Page = page;
            Results = results;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "last_page")]
        public bool? LastPage { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "num_results")]
        public long? NumResults { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "page")]
        public long? Page { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "results")]
        public IList<ListClinicalTrial> Results { get; set; }

    }
}
