// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace KnowledgeGraphSdk.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// data included from the search response
    /// </summary>
    public partial class SearchResponse
    {
        /// <summary>
        /// Initializes a new instance of the SearchResponse class.
        /// </summary>
        public SearchResponse() { }

        /// <summary>
        /// Initializes a new instance of the SearchResponse class.
        /// </summary>
        public SearchResponse(long? numResults = default(long?), long? page = default(long?), IList<ClinicalTrial> results = default(IList<ClinicalTrial>), long? totalPages = default(long?))
        {
            NumResults = numResults;
            Page = page;
            Results = results;
            TotalPages = totalPages;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "num_results")]
        public long? NumResults { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "page")]
        public long? Page { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "results")]
        public IList<ClinicalTrial> Results { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "total_pages")]
        public long? TotalPages { get; set; }

    }
}
