AWSTemplateFormatVersion: 2010-09-09

Description:
  Creates an EC2 with neo4j server.

Parameters:
  UserName:
    Type: String
    Default: kgadmin

  SSHPublicKey:
    Type: String

  BatchServerPublicKey:
    Type: String
    Default: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDVP2e6HpBEXw2fGB6dV+3YK1NQFx2ARVVJRnV3sH8KSI2BCm/zFL6z/seNirAvQsWlQ6hL1slmwWvMJQoAVUBEMUUlsVv55wb0HI0fA2YDS/qk8uTGVmaqI+uBmKDM6Wrifv5Tqny63euGQlVV0BwseYfn82c/YWMBK6bbSWHjEVVvXMUdIyQVAajBOmOhT/NyCW9iOATTO1O3A7HVvNEj16sFHd7l8GfjCqqptoTl8KU1IRY0vnn36DsEScJFyYesa6LVMrFmKryfTkliSQURsJ858dYM2EfsZUhXt3zMqpcunJJ7BfS2o7CENOF79emyMkAHZ00FK9mlFx+Hj02j kgadmin batch server key



  KeyName:
    Description: Keypair name
    Type: String

  ENV:
    Description: Environment
    Type: String

  ImageId:
    Description: AMI Id
    Type: String

  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.large
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large

    ConstraintDescription: must be a valid EC2 instance type.

Resources:

  NetworkInterface:
    Type: 'AWS::EC2::NetworkInterface'
    Properties:
      SubnetId:
        Fn::ImportValue:
          !Sub "kgraph-${ENV}-Subnet2Id"
      GroupSet:
        - Fn::ImportValue:
            !Sub "kgraph-${ENV}-SG-Neo4j"
        - Fn::ImportValue:
            !Sub "kgraph-${ENV}-SG-EFS"


  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      KeyName: !Ref KeyName
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      NetworkInterfaces:
        - NetworkInterfaceId: !Ref NetworkInterface
          DeviceIndex: '0'
      BlockDeviceMappings:
        -
          DeviceName: "/dev/sda1"
          Ebs:
            VolumeSize: 50
            VolumeType: gp2
      Tags:
        -
          Key: Name
          Value: !Sub "${ENV}-graphdb"

      UserData:
        Fn::Base64:
          !Sub
            - |
              #!/bin/bash -xe
              # Add kgadmin user and ssh public key to authorized keys
              adduser ${USERNAME}
              echo ${USERNAME} 'ALL=(ALL) NOPASSWD:ALL'>>/etc/sudoers.d/${USERNAME}
              mkdir /home/${USERNAME}/.ssh
              echo ${SSHKEY} > /home/${USERNAME}/.ssh/authorized_keys
              echo ${SSHKEY_BATCH_SERVER} >> /home/${USERNAME}/.ssh/authorized_keys
              chown -R ${USERNAME}.${USERNAME} /home/${USERNAME}/.ssh
              chmod 700 /home/${USERNAME}/.ssh
              chmod 600 /home/${USERNAME}/.ssh/authorized_keys

              # mount efs
              sudo mkdir -p /mnt/efs
              cd /home/${USERNAME}/
              git clone https://github.com/aws/efs-utils
              sudo apt-get -y install binutils
              cd efs-utils
              ./build-deb.sh
              sudo apt-get -y install ./build/amazon-efs-utils*deb
              sudo mount -t efs ${EFSID}:/ /mnt/efs
              chown -R ${USERNAME}.${USERNAME} /mnt/efs

              sudo echo "${EFSID}:/ /mnt/efs efs defaults,_netdev 0 0" >> /etc/fstab

              # update neo4j conf
              sudo sed -i "/dbms.directories.import=/ s/=.*/=\/mnt\/efs\/data/" /etc/neo4j/neo4j.template
              sudo sed -i '/^#dbms.tx_log.rotation.retention_policy.* /s/^#//' /etc/neo4j/neo4j.template
              sudo sed -i "/dbms.tx_log.rotation.retention_policy=/ s/=.*/=false/" /etc/neo4j/neo4j.template

              # install neosemantics plugin
              curl -s -L https://github.com/jbarrasa/neosemantics/releases/download/3.4.0.2/neosemantics-3.4.0.2.jar -o /var/lib/neo4j/plugins/neosemantics-3.4.0.2.jar &
              echo "dbms.unmanaged_extension_classes=semantics.extension=/rdf" >> /etc/neo4j/neo4j.template

              # restart neo4j
              sudo service neo4j restart

              sudo yum update -y
              # view results of this script at  /var/log/cloud-init-output.log
            - USERNAME: !Ref UserName
              SSHKEY: !Ref SSHPublicKey
              SSHKEY_BATCH_SERVER: !Ref BatchServerPublicKey
              EFSID:
                Fn::ImportValue:
                  !Sub "kgraph-${ENV}-EFSId"


  GraphDBEIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref EC2Instance

Outputs:
  InstanceId:
    Description: InstanceId of the instance
    Value: !Ref EC2Instance
    Export:
      Name: !Sub "kgraph-${ENV}-ec2-graphdb-server"

  GraphDBEIP:
    Description: Elastic IP of the graphdb server
    Value: !Ref GraphDBEIP
    Export:
      Name: !Sub "kgraph-${ENV}-eip-graphdb-server"
